'use strict';
const TOTAL=30;
const screens=[...document.querySelectorAll('.screen')],tabs=[...document.querySelectorAll('.tab')];
function showScreen(id){screens.forEach(s=>s.classList.toggle('active',s.id===id));tabs.forEach(t=>t.classList.toggle('active',t.dataset.screen===id));window.scrollTo({top:0,behavior:'smooth'});if(id==='challenge'&&!quiz.length)startQuiz()}
tabs.forEach(t=>t.addEventListener('click',()=>showScreen(t.dataset.screen)));document.querySelectorAll('[data-next]').forEach(b=>b.addEventListener('click',()=>showScreen(b.dataset.next)));
document.querySelectorAll('[data-practice]').forEach(b=>b.addEventListener('click',()=>{b.nextElementSibling.textContent='Answer: '+b.dataset.practice}));
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
const Q=(topic,prompt,display,options,answer,explanation)=>({topic,prompt,display,options,answer,explanation});
const bands=[
[
Q('Nouns','What is the main noun in this noun group?','the small red boat',['small','red','boat','the'],'boat','Boat is the person, place, thing or idea being described; the other words add information about it.'),
Q('Nouns','What is the main noun in this noun group?','those noisy rainbow lorikeets',['those','noisy','rainbow','lorikeets'],'lorikeets','Lorikeets is the main noun. The other words identify and describe the lorikeets.'),
Q('Noun Groups','Which option is an expanded noun group?','Choose the group with useful detail around a noun.',['tree','the tall gum tree','grew quickly','under the tree'],'the tall gum tree','The main noun is tree, expanded by the and tall gum.'),
Q('Noun Groups','Which option contains a noun group naming a person?','Choose one.',['ran quickly','the new science teacher','after lunch','was explaining'],'the new science teacher','Teacher is the main noun; the new science expands the group.'),
Q('Nouns','What is the main noun?','three old wooden chairs',['three','old','wooden','chairs'],'chairs','Chairs is the main noun. Three, old and wooden add information about the chairs.'),
Q('Noun Groups','Which words form the complete noun group?','The curious young fox crossed the road.',['The curious young fox','crossed','the road','young fox crossed'],'The curious young fox','The whole group identifies and describes the fox before the verb crossed.'),
Q('Nouns','Which word is the main noun?','our local community garden',['our','local','community','garden'],'garden','Garden is the main thing being named; the other words make its meaning more specific.'),
Q('Noun Groups','Which option is NOT a noun group?','Choose the option built around an action rather than a noun.',['the blue backpack','several native plants','ran across the oval','our school library'],'ran across the oval','Ran is a verb showing an action, so this option is not a noun group.')
],
[
Q('Expanding Before the Noun','Which expansion gives the clearest information about number and colour?','___ balloons',['balloons','the balloons','five yellow balloons','floating balloons'],'five yellow balloons','Five gives number and yellow gives colour, both adding clear information to the main noun balloons.'),
Q('Expanding Before the Noun','Which word tells how many?','the three young magpies',['the','three','young','magpies'],'three','Three gives the number of magpies.'),
Q('Expanding Before the Noun','Which word describes age?','an ancient stone wall',['an','ancient','stone','wall'],'ancient','Ancient describes the age of the wall.'),
Q('Expanding Before the Noun','Which noun group is most precise about which bottle is meant?','Choose one.',['a bottle','the bottle','the large blue water bottle','bottle'],'the large blue water bottle','Large, blue and water add identifying detail to the main noun bottle.'),
Q('Expanding Before the Noun','Which option correctly expands the noun “puppy” without changing the main noun?','Choose one.',['the playful brown puppy','the puppy barked','playfully barked','brownly puppy'],'the playful brown puppy','Puppy remains the main noun while the, playful and brown add description.'),
Q('Expanding Before the Noun','What is the main noun after this group is expanded?','the two enormous old fig trees',['two','enormous','fig','trees'],'trees','Expansion adds detail but does not change the main noun, trees.'),
Q('Expanding Before the Noun','Which added word gives size information?','the ___ suitcase',['wooden','huge','three','yesterday'],'huge','Huge describes the size of the suitcase.'),
Q('Expanding Before the Noun','Which noun group identifies a specific group most clearly?','A teacher is directing students to equipment.',['students','some students','the four students in blue shirts','people'],'the four students in blue shirts','The number and clothing detail distinguish this group from other students.')
],
[
Q('Adding Phrases','Which words add information after the main noun?','the bench near the library',['the bench','bench','near the library','the'],'near the library','Near the library comes after bench and tells which bench is meant.'),
Q('Adding Phrases','What is the main noun?','the seedlings beside the water tank',['seedlings','beside','water','tank'],'seedlings','Seedlings is the main noun; beside the water tank adds location information.'),
Q('Adding Phrases','Which noun group tells where the bicycle is?','Choose one.',['the red bicycle','the bicycle near the gate','the old bicycle','two bicycles'],'the bicycle near the gate','Near the gate adds location information after the main noun bicycle.'),
Q('Adding Phrases','Which expansion adds information after the noun “bridge”?','Choose one.',['the old bridge','the wooden bridge','the bridge across the creek','the narrow bridge'],'the bridge across the creek','Across the creek follows the main noun and adds location information.'),
Q('Adding Phrases','Which is the fullest noun group?','Choose the group that combines useful detail before and after the main noun.',['the shelter','the new shelter','the shelter beside the oval','the new weather shelter beside the oval'],'the new weather shelter beside the oval','It gives useful information both before and after the main noun shelter.'),
Q('Adding Phrases','Which words identify which students are meant?','the students from Year 5',['the students','from Year 5','Year 5','the'],'from Year 5','The phrase from Year 5 narrows the meaning of students to a particular group.'),
Q('Adding Phrases','Which noun group contains location detail after its main noun?','Choose one.',['the bright red kite','three large boxes','the path through the rainforest','our new teacher'],'the path through the rainforest','Through the rainforest follows path and gives location information.'),
Q('Adding Phrases','Which main noun is expanded by “on the eastern beach”?','the three juvenile turtles on the eastern beach',['three','juvenile','turtles','beach'],'turtles','The phrase on the eastern beach adds location information to the main noun turtles.')
],
[
Q('Precision','Which noun group is most useful in a wildlife observation?','The observer needs to record number, type and location.',['birds','beautiful birds','three rainbow lorikeets in the northern tree','some nice animals'],'three rainbow lorikeets in the northern tree','It supplies the requested number, type and location without irrelevant detail.'),
Q('Precision','Which noun group is most useful in a lost-property notice?','The item is a school bag that must be identified.',['a lovely thing','the bag','a large navy school bag with a red name tag','an interesting bag'],'a large navy school bag with a red name tag','The colour, type, size and name-tag detail help identify the missing item.'),
Q('Precision','Which detail is least useful in a factual weather report?','The report describes a storm approaching the coast.',['dark','storm','above the coast','delicious'],'delicious','Delicious describes taste and does not logically help describe a storm.'),
Q('Precision','Which noun group best suits an informative science sentence?','The sentence identifies a measured sample.',['stuff','the sample','the 50 mL water sample from Tank A','the amazing water'],'the 50 mL water sample from Tank A','The quantity, substance and source make the sample precise for an informative context.'),
Q('Precision','Which noun group best creates a mysterious atmosphere in a story?','Choose one.',['the path','the concrete path','the silent shadowy path beneath the trees','the 2-metre path'],'the silent shadowy path beneath the trees','Silent, shadowy and beneath the trees are relevant details for creating a mysterious atmosphere.'),
Q('Precision','Which revision removes irrelevant description from a safety instruction?','Original: Place the beautiful, cheerful, shiny red emergency cone beside the spill.',['Place the red emergency cone beside the spill.','Place the beautiful cheerful cone beside the spill.','Place the shiny cheerful red beautiful emergency cone beside the spill.','Place something beside the spill.'],'Place the red emergency cone beside the spill.','Red and emergency help identify the required safety item; beautiful and cheerful do not improve the instruction.'),
Q('Precision','Which noun group best identifies a location for a visitor?','Choose one.',['the room','a nice room','Room 12 beside the main office','the interesting room'],'Room 12 beside the main office','The room number and nearby landmark give useful identifying information.'),
Q('Precision','Why might a writer expand a noun group?','Choose the most accurate reason.',['To make every sentence longer','To provide fuller and more precise description when it helps the purpose','To avoid using nouns','To replace all verbs'],'To provide fuller and more precise description when it helps the purpose','Expanded noun groups add useful detail; effective writers select details according to purpose rather than simply adding length.')
],
[
Q('Application','Which revision most clearly improves the informative sentence?','Original: Birds nested in trees.',['Several rainbow lorikeets nested in the tall eucalyptus trees beside the oval.','Nice birds nested in nice trees.','Birds birds nested in trees trees.','Quickly nested under.'],'Several rainbow lorikeets nested in the tall eucalyptus trees beside the oval.','The revision adds specific type, quantity and location details while keeping the meaning clear.'),
Q('Application','Which noun group best completes a persuasive proposal?','Our school should plant ___ near the playground to improve shade.',['things','trees','several large native shade trees','beautiful stuff'],'several large native shade trees','The group specifies quantity, size, type and purpose-relevant qualities for the proposal.'),
Q('Application','Which sentence uses an expanded noun group without unnecessary repetition?','Choose one.',['The tall old gum tree beside the creek provides shade.','The tall old gum tree tree beside the creek tree provides shade.','The tree tall old beside provides creek shade.','The gum provides tree shade old.'],'The tall old gum tree beside the creek provides shade.','The noun group gives coherent detail around the single main noun tree.'),
Q('Application','Which main noun is being expanded?','our busy community park near the station',['busy','community','park','station'],'park','Park is the central noun; the other words identify and describe it.'),
Q('Application','Which revision makes the object easier to identify?','Original: Please collect the box.',['Please collect it.','Please collect the small green equipment box beside the storeroom door.','Please collect the wonderful box.','Please collect box quickly green.'],'Please collect the small green equipment box beside the storeroom door.','The added type, colour, size and location details distinguish the intended box.'),
Q('Application','Which sentence best suits an informative report?','Choose the sentence with precise, relevant noun groups.',['Some things were seen near there.','Two adult koalas were observed in the eucalyptus trees beside the walking track.','Two adorable cuddly amazing koalas were there.','Koalas things trees track.'],'Two adult koalas were observed in the eucalyptus trees beside the walking track.','The noun groups give number, age/type and location details appropriate to a factual report.'),
Q('Application','Which expansion changes “flowers” into a more precise noun group for a garden plan?','Choose one.',['flowers quickly','the six native flowering plants along the eastern fence','grew flowers','very flower'],'the six native flowers along the eastern fence','The group provides quantity, type and planned location while keeping flowers as the main noun.'),
Q('Application','Which noun group gives enough information to distinguish one shelter from others?','There are several shelters around the school.',['the shelter','a shelter','the new weather shelter beside the sports field','shelter'],'the new weather shelter beside the sports field','New, weather and beside the sports field provide identifying information.')
],
[
Q('Challenge','Which option expands the noun group while keeping every added detail relevant to a scientific observation?','The observer must identify four seedlings, their species and location.',['the four tomato seedlings beside Plot B','the four lovely exciting seedlings','seedlings that are wonderful','the plants'],'the four tomato seedlings beside Plot B','It supplies the required number, species and location with no irrelevant judgement.'),
Q('Challenge','Which revision gives fuller description without changing the basic fact?','Basic fact: A vehicle stopped near the gate.',['The white school minibus stopped near the front gate.','The vehicle suddenly became a gate.','The beautiful amazing wonderful thing stopped.','Near the gate vehicle white school.'],'The white school minibus stopped near the front gate.','The revision keeps the original event while making the vehicle and gate more specific.'),
Q('Challenge','Which noun group has useful information both before and after its main noun?','Choose one.',['the bridge','the old wooden bridge','the bridge across the creek','the old wooden bridge across the creek'],'the old wooden bridge across the creek','Old and wooden appear before bridge, while across the creek adds information after it.'),
Q('Challenge','Which sentence is most precise for an emergency instruction?','Choose one.',['Move the thing.','Move the red first-aid kit from the blocked doorway to the front desk.','Move the wonderful red kit somewhere.','Move a kit because it is nice.'],'Move the red first-aid kit from the blocked doorway to the front desk.','The noun groups clearly identify the item, its current location and its destination.'),
Q('Challenge','Which description best matches the purpose of a narrative trying to create tension?','A character approaches an abandoned building at night.',['the building','the large building at 14 Smith Street','the dark abandoned house at the end of the silent lane','the rectangular residential structure'],'the dark abandoned house at the end of the silent lane','The selected details support the narrative purpose by creating a tense atmosphere while remaining coherent.'),
Q('Challenge','Which edit improves precision by replacing a vague noun group?','Original: Put the stuff on the table.',['Put it there.','Put the three labelled science folders on the front table.','Put the nice stuff on a table.','Stuff table put.'],'Put the three labelled science folders on the front table.','The revised noun groups identify exactly what should be moved and where it should go.'),
Q('Challenge','Which statement about expanded noun groups is correct?','Choose one.',['They must always contain as many adjectives as possible.','They provide fuller description by adding useful information around a main noun.','They are used only in stories.','They replace the need for a main noun.'],'They provide fuller description by adding useful information around a main noun.','The main noun remains central while selected words and phrases expand its meaning for the text purpose.'),
Q('Challenge','Which version is most effective for a concise factual caption?','A photograph shows two newly hatched turtles moving toward the sea.',['Turtles.','Two newly hatched sea turtles moving toward the water.','Two incredibly adorable perfect little turtle creatures doing an amazing journey.','Moving newly two sea toward.'],'Two newly hatched sea turtles moving toward the water.','It includes the useful number, life-stage and type details while remaining concise and factual.')
]
];
function buildQuiz(){return bands.flatMap(b=>shuffle(b).slice(0,5))}
let quiz=[],index=0,score=0,answered=false,selected=null,attemptSaved=false;
const qn=document.getElementById('qNumber'),ql=document.getElementById('qLevel'),qs=document.getElementById('qScore'),qp=document.getElementById('quizProgress'),qt=document.getElementById('qTopic'),qprompt=document.getElementById('qPrompt'),qd=document.getElementById('qDisplay'),qa=document.getElementById('qAnswer'),qf=document.getElementById('qFeedback'),solution=document.getElementById('qSolution'),check=document.getElementById('checkAnswer'),next=document.getElementById('nextQuestion'),result=document.getElementById('resultCard');
function level(){return ['FOUNDATION','DEVELOPING','CONNECTING','PROFICIENT','APPLICATION','CHALLENGE'][Math.floor(index/5)]}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function render(){const q=quiz[index];answered=false;selected=null;qn.textContent=(index+1)+' / '+TOTAL;ql.textContent=level();qs.textContent=score+' / '+TOTAL;qp.style.width=(((index+1)/TOTAL)*100)+'%';qt.textContent=q.topic;qprompt.textContent=q.prompt;qd.innerHTML='<div class="prompt-card">'+esc(q.display)+'</div>';qf.textContent='';qf.className='q-feedback';solution.hidden=true;solution.innerHTML='';check.disabled=false;next.disabled=true;qa.innerHTML='<div class="choice-wrap">'+shuffle(q.options).map(o=>'<button type="button" data-choice="'+esc(o)+'">'+esc(o)+'</button>').join('')+'</div>';qa.querySelectorAll('[data-choice]').forEach(b=>b.addEventListener('click',()=>{if(answered)return;selected=b.dataset.choice;qa.querySelectorAll('button').forEach(x=>x.classList.toggle('selected',x===b));qf.textContent=''}))}
check.addEventListener('click',()=>{if(answered)return;if(selected===null){qf.textContent='Choose one answer first.';return}const q=quiz[index],ok=selected===q.answer;answered=true;if(ok){score++;qf.textContent='Correct!';qf.className='q-feedback correct'}else{qf.textContent='Not quite. Read the explanation below.';qf.className='q-feedback incorrect';solution.hidden=false;solution.innerHTML='<h4>Why?</h4><p>'+esc(q.explanation)+'</p><p><strong>Best answer: '+esc(q.answer)+'</strong></p>'}qs.textContent=score+' / '+TOTAL;check.disabled=true;next.disabled=false;qa.querySelectorAll('button').forEach(x=>x.disabled=true)});
next.addEventListener('click',()=>{if(index<TOTAL-1){index++;render()}else finish()});document.getElementById('restartQuiz').addEventListener('click',startQuiz);
function startQuiz(){quiz=buildQuiz();index=0;score=0;attemptSaved=false;document.querySelector('.quiz-card').hidden=false;result.hidden=true;render()}
async function finish(){document.querySelector('.quiz-card').hidden=true;result.hidden=false;const pct=Math.round(score/TOTAL*100);const msg=score===TOTAL?'Perfect score — proficiency achieved!':pct>=85?'Excellent understanding.':pct>=70?'Strong work. Review the explanations for any missed questions.':pct>=50?'Good progress. Revisit the learning pages before another attempt.':'Revisit Pages 1–5, then try a new challenge.';result.innerHTML='<p class="tag">CHALLENGE COMPLETE</p><h2>'+pct+'%</h2><strong>'+score+' out of '+TOTAL+' correct</strong><p>'+msg+'</p><p id="saveStatus">Recording completed attempt…</p>';if(attemptSaved)return;attemptSaved=true;const status=document.getElementById('saveStatus');try{let tries=0;while(!window.WordMagicNounGroupProgress?.saveAttempt&&tries<30){await new Promise(r=>setTimeout(r,100));tries++}if(!window.WordMagicNounGroupProgress?.saveAttempt)throw new Error('Progress service unavailable');const p=await window.WordMagicNounGroupProgress.saveAttempt(score);status.textContent='✓ Attempt recorded • '+Math.min(p.attempts,5)+'/5 completed • Best '+p.bestScore+'/'+TOTAL+(p.proficient?' • PROFICIENT':'')}catch(e){console.error('Progress save failed:',e);attemptSaved=false;status.textContent='This attempt could not be recorded. Please keep this page open and try again.';status.className='incorrect'}}
