'use strict';
const TOTAL=30;
const screens=[...document.querySelectorAll('.screen')],tabs=[...document.querySelectorAll('.tab')];
function showScreen(id){screens.forEach(s=>s.classList.toggle('active',s.id===id));tabs.forEach(t=>t.classList.toggle('active',t.dataset.screen===id));window.scrollTo({top:0,behavior:'smooth'});if(id==='challenge'&&!quiz.length)startQuiz()}
tabs.forEach(t=>t.addEventListener('click',()=>showScreen(t.dataset.screen)));document.querySelectorAll('[data-next]').forEach(b=>b.addEventListener('click',()=>showScreen(b.dataset.next)));
document.querySelectorAll('[data-practice]').forEach(b=>b.addEventListener('click',()=>{b.nextElementSibling.textContent='Answer: '+b.dataset.practice}));
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
const Q=(topic,prompt,display,options,answer,explanation)=>({topic,prompt,display,options,answer,explanation});
const bands=[
[
Q('Complete Sentences','Which option is a complete sentence?','Choose the option that expresses a complete idea.',['Because the rain stopped.','The rain stopped.','When the rain stopped.','Although the rain stopped.'],'The rain stopped.','“The rain stopped.” can stand alone and expresses a complete idea. The other options begin with words that make the clause depend on more information.'),
Q('Complete Sentences','Which option can stand alone as a sentence?','Look for a complete idea.',['After the bell rang.','While the class waited.','The teacher opened the door.','Because the lesson ended.'],'The teacher opened the door.','“The teacher opened the door.” contains a subject and verb and expresses a complete idea.'),
Q('Clauses','Which group of words is a main clause?','A main clause can stand alone.',['if the wind changes','the kite will rise','although it is cloudy','when we reach the oval'],'the kite will rise','“The kite will rise” can stand alone as a complete sentence, so it is a main clause.'),
Q('Clauses','Which group of words is a dependent clause?','A dependent clause needs a main clause to complete its meaning.',['the dog barked','our team practised','because the gate was open','Mia packed her bag'],'because the gate was open','“Because the gate was open” begins with “because” and leaves the reader waiting for the result.'),
Q('Sentence Meaning','Which sentence clearly states one complete idea?','Choose the grammatically complete option.',['The scientist recorded the result.','Although the scientist recorded.','Because the result.','When recording the result.'],'The scientist recorded the result.','The first option has a clear subject, verb and complete idea.'),
Q('Clauses','In the sentence below, which words form the main clause?','When the sun appeared, the children returned to the playground.',['When the sun appeared','the children returned to the playground','When the sun','to the playground'],'the children returned to the playground','“The children returned to the playground” can stand alone. “When the sun appeared” adds time information.'),
Q('Clauses','In the sentence below, which words form the dependent clause?','Although the water was cold, Lena continued swimming.',['Lena continued swimming','Although the water was cold','the water was cold','continued swimming'],'Although the water was cold','The clause beginning with “although” depends on the main clause and adds a contrast.'),
Q('Complete Sentences','Which option is NOT a complete sentence?','Choose the option that needs another clause.',['The library closes at five.','Our class borrowed three books.','Because the library was busy.','The librarian helped us.'],'Because the library was busy.','The word “because” introduces a reason, but the sentence does not tell us what happened as a result.')
],
[
Q('Complex Sentences','Which sentence is complex?','A complex sentence has a main clause and at least one dependent clause.',['The rain fell and the wind blew.','We stayed inside because the storm was severe.','The storm was severe.','We stayed inside.'],'We stayed inside because the storm was severe.','It combines the main clause “We stayed inside” with the dependent clause “because the storm was severe.”'),
Q('Relationships','Which word best completes the sentence to show a reason?','We moved the picnic indoors ___ dark clouds were approaching.',['although','because','if','before'],'because','“Because” introduces the reason the picnic was moved indoors.'),
Q('Relationships','Which word best completes the sentence to show a condition?','___ the weather improves, we will play outside.',['Because','Although','If','After'],'If','“If” introduces a condition: playing outside depends on the weather improving.'),
Q('Relationships','Which word best completes the sentence to show contrast?','___ the puzzle was difficult, Aria kept working.',['Although','Because','When','After'],'Although','“Although” signals a contrast between the difficulty and Aria continuing.'),
Q('Relationships','Which word best completes the sentence to show time?','We packed our bags ___ the excursion ended.',['because','although','after','if'],'after','“After” clearly shows that packing happened later than the excursion ending.'),
Q('Complex Sentences','Which option correctly joins the ideas to show cause?','Idea 1: The path was flooded. Idea 2: We chose another route.',['We chose another route because the path was flooded.','Although the path was flooded, we chose another route because.','If the path was flooded, because we chose another route.','We chose another route although the path was flooded because.'],'We chose another route because the path was flooded.','The sentence clearly presents the result and then its cause.'),
Q('Complex Sentences','Which sentence contains a dependent clause first?','Look at the order of the clauses.',['The match continued because the rain stopped.','When the rain stopped, the match continued.','The rain stopped and the match continued.','The match continued.'],'When the rain stopped, the match continued.','“When the rain stopped” is the dependent clause and it appears before the main clause.'),
Q('Clause Purpose','What does the dependent clause add in this sentence?','Before the gates opened, the crowd formed a line.',['a reason','a contrast','a time relationship','a condition'],'a time relationship','“Before the gates opened” tells when the crowd formed a line.')
],
[
Q('Cohesion','Which connective best signals a result?','The soil was very dry. ___, we watered the garden.',['For example','Therefore','Meanwhile','First'],'Therefore','“Therefore” signals that watering the garden is a result of the dry soil.'),
Q('Cohesion','Which connective best signals an example?','Many native animals are active at night. ___, possums often search for food after dark.',['For example','Therefore','However','Finally'],'For example','The second sentence gives a specific example of the first statement.'),
Q('Cohesion','Which connective best signals contrast?','The morning was sunny. ___, heavy rain arrived in the afternoon.',['Similarly','However','Therefore','For example'],'However','“However” signals a contrast between the sunny morning and rainy afternoon.'),
Q('Cohesion','Which opening best continues the sequence?','First, wash the strawberries. Next, slice them carefully. ___, place them in the bowl.',['Finally','However','Because','For example'],'Finally','“Finally” clearly signals the last step in the sequence.'),
Q('Pronoun Reference','Which sentence has the clearest pronoun reference?','Choose the sentence in which “she” clearly refers to one person.',['Mia spoke to Ava after she finished the race.','After Mia finished the race, she collected her medal.','Mia thanked Ava because she was helpful.','Mia met Ava when she arrived.'],'After Mia finished the race, she collected her medal.','The opening clause names Mia as the person who finished the race, so “she” clearly continues to refer to Mia.'),
Q('Cohesion','Which pair is most cohesive?','Look for a clear connection between the two sentences.',['The class planted herbs. These plants will be used in the cooking lesson.','The class planted herbs. However, triangles have three sides.','The class planted herbs. Therefore, the moon orbits Earth.','The class planted herbs. Meanwhile, seven is a prime number.'],'The class planted herbs. These plants will be used in the cooking lesson.','“These plants” clearly refers back to the herbs and develops the same idea.'),
Q('Cohesion','Which connective best shows two events happening at the same time?','Luca prepared the slides. ___, Priya checked the microphone.',['Meanwhile','Therefore','For example','Finally'],'Meanwhile','“Meanwhile” shows that Priya’s action happened during the same period as Luca’s.'),
Q('Cohesion','Which sentence opening best guides the reader to an additional similar point?','Solar panels can reduce electricity drawn from the grid. ___, good insulation can reduce the energy needed for heating and cooling.',['Similarly','However','As a result','Yesterday'],'Similarly','“Similarly” signals that the second idea is another related way to reduce energy use.')
],
[
Q('Writer’s Choices','Which version gives the windy condition greater prominence by placing it first?','Compare the starting point of each sentence.',['The team continued although the wind was strong.','Although the wind was strong, the team continued.','The team continued and the wind was strong.','The wind was strong.'],'Although the wind was strong, the team continued.','Placing the dependent clause first makes the difficult condition the starting point of the message.'),
Q('Writer’s Choices','Which sentence best emphasises the time of the discovery by placing it first?','The discovery happened after lunch.',['The students found the missing key after lunch.','After lunch, the students found the missing key.','The students found the key.','The missing key was small.'],'After lunch, the students found the missing key.','Starting with “After lunch” gives the time information prominence.'),
Q('Cohesive Paragraphs','Which sentence best follows the opening sentence?','Opening: The class wanted to reduce lunchtime waste.',['Therefore, students set up labelled recycling and compost bins.','Meanwhile, whales migrate long distances.','For example, the oval was wet yesterday.','However, fractions can be equivalent.'],'Therefore, students set up labelled recycling and compost bins.','“Therefore” links the action directly to the class goal and develops the same topic.'),
Q('Relationships','Which sentence most clearly shows that the second event happened because of the first?','Choose the clearest cause-and-effect relationship.',['The alarm sounded, and we left the room.','Because the alarm sounded, we left the room.','Although the alarm sounded, we left the room.','Before the alarm sounded, we left the room.'],'Because the alarm sounded, we left the room.','“Because” explicitly marks the alarm as the reason for leaving.'),
Q('Editing','Which revision fixes the incomplete sentence?','Original: Because the oval was too wet.',['Because the oval was too wet, the game was moved indoors.','Because the oval.','The game because the oval was too wet.','Although because the oval was wet.'],'Because the oval was too wet, the game was moved indoors.','The revision adds a main clause, completing the idea introduced by “because.”'),
Q('Editing','Which revision creates a clear complex sentence showing contrast?','Ideas: The climb was steep. We reached the lookout.',['Although the climb was steep, we reached the lookout.','Because the climb was steep, although we reached the lookout.','The climb was steep because we reached the lookout.','If the climb was steep, because we reached the lookout.'],'Although the climb was steep, we reached the lookout.','“Although” clearly marks the contrast between the difficult climb and reaching the lookout.'),
Q('Writer’s Choices','Which opening best puts the reason first?','The event was postponed because the hall was unavailable.',['Because the hall was unavailable, the event was postponed.','The event was postponed because the hall was unavailable.','The event was postponed.','The hall was unavailable.'],'Because the hall was unavailable, the event was postponed.','The reason is moved to the sentence starting point, giving it greater prominence.'),
Q('Cohesion','Which revision avoids unnecessary repetition while keeping the reference clear?','Original: Noah found Noah’s notebook. Noah put Noah’s notebook in Noah’s bag.',['Noah found his notebook and put it in his bag.','He found it and put it there.','Noah found Noah’s notebook, Noah put notebook bag.','His notebook found Noah and it put him there.'],'Noah found his notebook and put it in his bag.','The pronouns have clear referents and remove unnecessary repetition without losing meaning.')
],
[
Q('Application','Which sentence best links the evidence to the conclusion?','The thermometer showed 39°C. The pavement felt extremely hot. ___, the class moved the activity indoors.',['As a result','For example','Meanwhile','In contrast'],'As a result','The final action results from the hot conditions described in the first two sentences.'),
Q('Application','Which sentence best continues the paragraph cohesively?','Mangroves protect coastlines from waves. Their roots also provide shelter for young fish.',['These features make mangroves important coastal habitats.','However, basketball uses a round ball.','Next, the number twelve has six factors.','Because the telescope was new.'],'These features make mangroves important coastal habitats.','“These features” refers to the two benefits already described and draws them together.'),
Q('Application','Which sentence makes the conditional relationship clearest?','The team will qualify only if it wins the final match.',['If the team wins the final match, it will qualify.','Because the team wins, it qualified yesterday.','Although the team wins, if it qualifies.','The team qualifies and the final match.'],'If the team wins the final match, it will qualify.','The “if” clause clearly states the condition required for qualification.'),
Q('Application','Which version best guides the reader through a process?','Choose the most cohesive sequence.',['First, collect the data. Next, organise it in a table. Finally, identify the pattern.','Collect the data. However, organise it. For example, identify the pattern.','Finally, collect the data. First, identify the pattern. Next, organise it.','Collect because data. Although table. Finally pattern.'],'First, collect the data. Next, organise it in a table. Finally, identify the pattern.','The sequence connectives match the logical order of the process.'),
Q('Application','Which sentence best combines the ideas without changing their relationship?','Ideas: The battery was flat. The device would not start.',['The device would not start because the battery was flat.','Although the battery was flat, the device would not start.','If the device would not start, the battery was flat.','Before the battery was flat, the device would not start.'],'The device would not start because the battery was flat.','“Because” correctly identifies the flat battery as the cause.'),
Q('Application','Which sentence opening most clearly shifts from a benefit to a drawback?','Cycling to school can reduce traffic. ___, riding in heavy rain can be uncomfortable.',['However','Similarly','Therefore','For example'],'However','“However” signals a contrast between the benefit and the drawback.'),
Q('Application','Which paragraph has the clearest pronoun reference?','Choose the option where each pronoun has an obvious referent.',['Leila handed the camera to Zoe. She checked its battery.','Leila picked up the camera. She checked its battery before using it.','Leila met Zoe near Mia. She checked it.','Leila gave Zoe Mia’s camera because she needed it.'],'Leila picked up the camera. She checked its battery before using it.','Only Leila is introduced as a person in the first sentence, and “its” clearly refers to the camera.'),
Q('Application','Which sentence best foregrounds the condition for safety?','The hikers will continue if the weather remains safe.',['If the weather remains safe, the hikers will continue.','The hikers will continue if the weather remains safe.','The hikers will continue.','The weather remains safe.'],'If the weather remains safe, the hikers will continue.','Moving the “if” clause to the beginning makes the safety condition the starting point.')
],
[
Q('Challenge','Which revision creates the clearest logical relationship?','Original ideas: The experiment was repeated. The first result was unusual.',['The experiment was repeated because the first result was unusual.','Although the experiment was repeated, the first result was unusual because.','If the first result was unusual although the experiment repeated.','The experiment was repeated before because the result was unusual.'],'The experiment was repeated because the first result was unusual.','The sentence explicitly and logically identifies the unusual first result as the reason for repeating the experiment.'),
Q('Challenge','Which option best improves cohesion without adding a new idea?','The school installed a water tank. The water tank collects rain from the library roof. The water tank supplies the garden.',['The school installed a water tank. It collects rain from the library roof and supplies the garden.','The school installed a water tank. However, planets orbit stars.','The school installed it. It does things there.','Water tank school library garden rain.'],'The school installed a water tank. It collects rain from the library roof and supplies the garden.','The pronoun “it” clearly refers to the water tank and removes unnecessary repetition.'),
Q('Challenge','Which connective best fits the precise relationship?','The first design was inexpensive. ___, it was not strong enough for repeated use.',['However','Therefore','For example','Similarly'],'However','The second sentence contrasts a disadvantage with the first sentence’s advantage.'),
Q('Challenge','Which sentence uses clause order to foreground an obstacle?','Choose the sentence that starts with the obstacle.',['We completed the survey although several students were absent.','Although several students were absent, we completed the survey.','We completed the survey.','Several students were absent and we completed the survey.'],'Although several students were absent, we completed the survey.','The obstacle is placed in the opening dependent clause, so it becomes the starting point for the reader.'),
Q('Challenge','Which sentence best expresses an unexpected contrast?','The power failed. The presentation continued using printed notes.',['Although the power failed, the presentation continued using printed notes.','Because the power failed, the presentation continued using printed notes.','If the power failed, the presentation continued using printed notes.','After the presentation continued, the power failed because.'],'Although the power failed, the presentation continued using printed notes.','“Although” clearly signals the unexpected contrast between the power failure and the presentation continuing.'),
Q('Challenge','Which continuation makes the paragraph most cohesive?','The creek level rose rapidly overnight. By morning, water covered the low bridge.',['As a result, the council closed the crossing.','For example, the library added new books.','Similarly, triangles can be classified by sides.','Meanwhile, a recipe used two cups of flour.'],'As a result, the council closed the crossing.','The closure is a logical result of the rising water and covered bridge.'),
Q('Challenge','Which revision most clearly shows time first and cause second?','Ideas: After lunch, the class moved indoors because thunder was heard.',['After lunch, the class moved indoors because thunder was heard.','Because thunder was heard, after lunch the class moved indoors.','The class moved indoors although after lunch because thunder.','If lunch ended, thunder because the class moved.'],'After lunch, the class moved indoors because thunder was heard.','The sentence begins with time (“After lunch”) and later gives the cause (“because thunder was heard”).'),
Q('Challenge','Which sentence is a complex sentence with a clear condition?','Choose the option with one main clause and a dependent “if” clause.',['If the sensor detects smoke, the alarm will sound.','The sensor detects smoke and the alarm sounds.','The alarm will sound.','Smoke and the sensor alarm.'],'If the sensor detects smoke, the alarm will sound.','The “if” clause states the condition, and “the alarm will sound” is the main clause.')
]
];
function buildQuiz(){return bands.flatMap(b=>shuffle(b).slice(0,5))}
let quiz=[],index=0,score=0,answered=false,selected=null,attemptSaved=false;
const qn=document.getElementById('qNumber'),ql=document.getElementById('qLevel'),qs=document.getElementById('qScore'),qp=document.getElementById('quizProgress'),qt=document.getElementById('qTopic'),qprompt=document.getElementById('qPrompt'),qd=document.getElementById('qDisplay'),qa=document.getElementById('qAnswer'),qf=document.getElementById('qFeedback'),solution=document.getElementById('qSolution'),check=document.getElementById('checkAnswer'),next=document.getElementById('nextQuestion'),result=document.getElementById('resultCard');
function level(){return ['FOUNDATION','DEVELOPING','CONNECTING','PROFICIENT','APPLICATION','CHALLENGE'][Math.floor(index/5)]}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function render(){const q=quiz[index];answered=false;selected=null;qn.textContent=(index+1)+' / '+TOTAL;ql.textContent=level();qs.textContent=score+' / '+TOTAL;qp.style.width=(((index+1)/TOTAL)*100)+'%';qt.textContent=q.topic;qprompt.textContent=q.prompt;qd.innerHTML='<div class="prompt-card">'+esc(q.display)+'</div>';qf.textContent='';qf.className='q-feedback';solution.hidden=true;solution.innerHTML='';check.disabled=false;next.disabled=true;qa.innerHTML='<div class="choice-wrap">'+shuffle(q.options).map(o=>'<button type="button" data-choice="'+esc(o)+'">'+esc(o)+'</button>').join('')+'</div>';qa.querySelectorAll('[data-choice]').forEach(b=>b.addEventListener('click',()=>{if(answered)return;selected=b.dataset.choice;qa.querySelectorAll('button').forEach(x=>x.classList.toggle('selected',x===b));qf.textContent=''}))}
check.addEventListener('click',()=>{if(answered)return;if(selected===null){qf.textContent='Choose one answer first.';return}const q=quiz[index],ok=selected===q.answer;answered=true;if(ok){score++;qf.textContent='Correct!';qf.className='q-feedback correct'}else{qf.textContent='Not quite. Read the explanation below.';qf.className='q-feedback incorrect';solution.hidden=false;solution.innerHTML='<h4>Why?</h4><p>'+esc(q.explanation)+'</p><p><strong>Best answer: '+esc(q.answer)+'</strong></p>'}qs.textContent=score+' / '+TOTAL;check.disabled=true;next.disabled=false;qa.querySelectorAll('button').forEach(x=>x.disabled=true)});
next.addEventListener('click',()=>{if(index<TOTAL-1){index++;render()}else finish()});document.getElementById('restartQuiz').addEventListener('click',startQuiz);
function startQuiz(){quiz=buildQuiz();index=0;score=0;attemptSaved=false;document.querySelector('.quiz-card').hidden=false;result.hidden=true;render()}
async function finish(){document.querySelector('.quiz-card').hidden=true;result.hidden=false;const pct=Math.round(score/TOTAL*100);const msg=score===TOTAL?'Perfect score — proficiency achieved!':pct>=85?'Excellent understanding.':pct>=70?'Strong work. Review the explanations for any missed questions.':pct>=50?'Good progress. Revisit the learning pages before another attempt.':'Revisit Pages 1–5, then try a new challenge.';result.innerHTML='<p class="tag">CHALLENGE COMPLETE</p><h2>'+pct+'%</h2><strong>'+score+' out of '+TOTAL+' correct</strong><p>'+msg+'</p><p id="saveStatus">Recording completed attempt…</p>';if(attemptSaved)return;attemptSaved=true;const status=document.getElementById('saveStatus');try{let tries=0;while(!window.WordMagicSentenceProgress?.saveAttempt&&tries<30){await new Promise(r=>setTimeout(r,100));tries++}if(!window.WordMagicSentenceProgress?.saveAttempt)throw new Error('Progress service unavailable');const p=await window.WordMagicSentenceProgress.saveAttempt(score);status.textContent='✓ Attempt recorded • '+Math.min(p.attempts,5)+'/5 completed • Best '+p.bestScore+'/'+TOTAL+(p.proficient?' • PROFICIENT':'')}catch(e){console.error('Progress save failed:',e);attemptSaved=false;status.textContent='This attempt could not be recorded. Please keep this page open and try again.';status.className='incorrect'}}
