import { initializeApp } from "https://www.gstatic.com/firebasejs/12.3.0/firebase-app.js";
import { getAuth,onAuthStateChanged,signOut } from "https://www.gstatic.com/firebasejs/12.3.0/firebase-auth.js";
import { getFirestore,doc,getDoc,setDoc } from "https://www.gstatic.com/firebasejs/12.3.0/firebase-firestore.js";
import { firebaseConfig } from "./firebase-config.js";
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),topicId="sentences-clauses-cohesion";
const key=uid=>"wordmagic:"+uid+":"+topicId+":progress",ref=uid=>doc(db,"progress",uid,"topics",topicId);
function clean(d={}){return{attempts:Number(d.attempts||0),bestScore:Number(d.bestScore||0),lastScore:Number(d.lastScore||0),proficient:d.proficient===true,lastCompletedAt:d.lastCompletedAt||null}}
function localRead(uid){try{return clean(JSON.parse(localStorage.getItem(key(uid))||"{}"))}catch{return clean()}}
function localSave(uid,d){localStorage.setItem(key(uid),JSON.stringify(d))}
function paint(d={}){const p=clean(d),a=p.attempts;const dots=document.getElementById("attemptDots"),at=document.getElementById("attemptText"),best=document.getElementById("bestText"),prof=document.getElementById("proficiencyText");if(dots)dots.textContent=Array.from({length:5},(_,i)=>i<Math.min(a,5)?"●":"○").join(" ");if(at)at.textContent=a<5?a+" of 5 completed":"5 of 5 minimum completed • "+a+" total attempts";if(best)best.textContent=a?"Best: "+p.bestScore+"/30":"Best: —";if(prof){prof.textContent=p.proficient?"✓ PROFICIENT":a>0?"Proficiency: In progress":"Proficiency: Start";prof.classList.toggle("proficient",p.proficient)}}
async function load(uid){const s=await getDoc(ref(uid));if(s.exists()){const p=clean(s.data());localSave(uid,p);return p}const p=localRead(uid);if(p.attempts>0)await setDoc(ref(uid),p);return p}
onAuthStateChanged(auth,async user=>{if(!user){location.replace("index.html");return}try{const access=await getDoc(doc(db,"access",user.uid));if(!(access.exists()&&access.data().approved===true)){location.replace("access-required.html");return}paint(await load(user.uid));window.WordMagicSentenceProgress={async saveAttempt(score){const old=await load(user.uid),data={attempts:old.attempts+1,bestScore:Math.max(old.bestScore,Number(score||0)),lastScore:Number(score||0),proficient:old.proficient||Number(score)===30,lastCompletedAt:new Date().toISOString()};await setDoc(ref(user.uid),data);localSave(user.uid,data);paint(data);return data}};document.body.classList.remove("auth-loading")}catch(e){console.error("WordMagic access/progress check failed:",e);location.replace("access-required.html?error=1")}});
document.getElementById("logoutBtn")?.addEventListener("click",async()=>{await signOut(auth);location.replace("index.html")});